services:
  ormt-minio:
    # coollabsio/minio:RELEASE.2025-10-15T17-29-55Z
    image: ghcr.io/coollabsio/minio@sha256:69b55a1c1c5dc285ce04db96689f5b2102317fc77a50680a1874ca6efd1c87f9
    healthcheck:
      test: ["CMD-SHELL", "mc alias set health http://127.0.0.1:9000 \"$$MINIO_ROOT_USER\" \"$$MINIO_ROOT_PASSWORD\" >/dev/null && mc ready health"]
  minio-bootstrap:
    image: ghcr.io/coollabsio/minio@sha256:69b55a1c1c5dc285ce04db96689f5b2102317fc77a50680a1874ca6efd1c87f9
